# Generated by Django 5.1.1 on 2024-10-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('okay', 'Okay')], default='pending', max_length=10),
        ),
    ]
