# Generated by Django 5.1.1 on 2024-10-05 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exam_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='answers/')),
                ('status', models.CharField(choices=[('checked', 'Checked'), ('unchecked', 'Unchecked'), ('okay', 'Okay')], default='unchecked', max_length=10)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
            ],
        ),
    ]
