# Generated by Django 5.1.1 on 2024-10-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_answerscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerscript',
            name='answer',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.FileField(upload_to=''),
        ),
    ]
