# Generated by Django 5.1.1 on 2024-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
