# Generated by Django 5.1.1 on 2024-10-07 14:55

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='folder',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent_folder', 'user_profile')},
        ),
    ]
