# Generated by Django 5.1.1 on 2024-10-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_history_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
