# Generated by Django 5.1.1 on 2024-10-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_history_daycount_alter_history_last_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='month_year',
            field=models.CharField(max_length=20),
        ),
    ]
