# Generated by Django 5.1.1 on 2024-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='reated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
