# Generated by Django 5.1.1 on 2024-10-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_reated_at_history_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='example@gamil.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
